name: restaurant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  http: ^1.2.2
  provider: ^6.1.2
  google_fonts: ^6.2.1
  readmore: ^3.0.0
  flutter_timezone: ^4.0.0
  timezone: ^0.10.0
  flutter_local_notifications: ^18.0.1
  mocktail: ^1.0.4
  sqflite: ^2.4.1
  shared_preferences: ^2.5.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.8

flutter:
  uses-material-design: true
